// <auto-generated />
using System;
using Garage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage.Migrations
{
    [DbContext(typeof(GarageContext))]
    [Migration("20251217140406_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ParkTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volvo",
                            Color = "Red",
                            Model = "XC60",
                            ParkTime = new DateTime(2025, 12, 17, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Registration = "ABC123",
                            VehicleType = 0,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Yamaha",
                            Color = "Black",
                            Model = "MT-07",
                            ParkTime = new DateTime(2025, 12, 17, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Registration = "MOTO77",
                            VehicleType = 1,
                            Wheels = 2
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Polaris",
                            Color = "Green",
                            Model = "Sportsman",
                            ParkTime = new DateTime(2025, 12, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Registration = "ATV999",
                            VehicleType = 2,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Scania",
                            Color = "White",
                            Model = "Citywide",
                            ParkTime = new DateTime(2025, 12, 17, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            Registration = "BUS001",
                            VehicleType = 3,
                            Wheels = 6
                        },
                        new
                        {
                            Id = 5,
                            Brand = "MAN",
                            Color = "Blue",
                            Model = "TGX",
                            ParkTime = new DateTime(2025, 12, 17, 7, 20, 0, 0, DateTimeKind.Unspecified),
                            Registration = "TRK888",
                            VehicleType = 4,
                            Wheels = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
